services:
  - type: web
    name: starlink-flask-app
    env: python
    pythonVersion: 3.11.8       # Force 3.11.8 here!
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app --bind 0.0.0.0:$PORT