services:
  - type: web
    name: starlink-flask-app
    env: python
    pythonVersion: 3.11.8          # THIS actually forces Python 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"